# Generated by Django 5.2.1 on 2025-06-24 20:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('password_changed', 'Password Changed'), ('newsletter_confirmation', 'Newsletter Confirmation'), ('content_upload', 'Content Upload Notification'), ('live_video', 'Live Video Notification'), ('weekly_digest', 'Weekly Digest'), ('monthly_newsletter', 'Monthly Newsletter'), ('password_reset', 'Password Reset'), ('account_verification', 'Account Verification')], max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked')], default='pending', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Notification',
                'verbose_name_plural': 'Email Notifications',
                'db_table': 'email_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_email', 'notification_type'], name='email_notif_recipie_db34d5_idx'), models.Index(fields=['status', 'created_at'], name='email_notif_status_026b4d_idx'), models.Index(fields=['notification_type', 'created_at'], name='email_notif_notific_09b9c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('password_changed', 'Password Changed'), ('newsletter_confirmation', 'Newsletter Confirmation'), ('content_upload', 'Content Upload Notification'), ('live_video', 'Live Video Notification'), ('weekly_digest', 'Weekly Digest'), ('monthly_newsletter', 'Monthly Newsletter')], max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField(help_text='HTML email template')),
                ('text_content', models.TextField(help_text='Plain text email template')),
                ('variables', models.JSONField(default=dict, help_text='Available template variables and their descriptions')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_templates',
                'ordering': ['-created_at'],
                'unique_together': {('template_type', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=100)),
                ('content_uploads', models.BooleanField(default=True, help_text='Notify about new content uploads')),
                ('live_videos', models.BooleanField(default=True, help_text='Notify about live streams')),
                ('weekly_digest', models.BooleanField(default=True, help_text='Weekly digest of content')),
                ('monthly_newsletter', models.BooleanField(default=True, help_text='Monthly newsletter')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_source', models.CharField(choices=[('footer', 'Footer Subscription'), ('popup', 'Popup Modal'), ('account_creation', 'Account Creation'), ('profile_settings', 'Profile Settings')], default='footer', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, help_text='Linked user account if exists', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'db_table': 'newsletter_subscriptions',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email', 'is_active'], name='newsletter__email_bbcf65_idx'), models.Index(fields=['is_verified', 'is_active'], name='newsletter__is_veri_5a9481_idx'), models.Index(fields=['subscribed_at'], name='newsletter__subscri_497fe4_idx')],
            },
        ),
    ]
