# Generated by Django 5.2.1 on 2025-06-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianimationrequest',
            name='animation',
        ),
        migrations.RemoveField(
            model_name='aianimationrequest',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='animation',
            name='animations__is_ai_g_583173_idx',
        ),
        migrations.RemoveField(
            model_name='animation',
            name='ai_model_used',
        ),
        migrations.RemoveField(
            model_name='animation',
            name='ai_prompt',
        ),
        migrations.RemoveField(
            model_name='animation',
            name='generation_parameters',
        ),
        migrations.RemoveField(
            model_name='animation',
            name='is_ai_generated',
        ),
        migrations.DeleteModel(
            name='AIAnimationRequest',
        ),
    ]
