# Generated by Django 5.2.1 on 2025-06-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_create_missing_useractivity'),
        ('authapp', '0007_alter_user_avatar'),
    ]

    operations = [
    ]
