# Generated by Django 5.2.1 on 2025-06-15 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('new_users_today', models.PositiveIntegerField(default=0)),
                ('active_users_today', models.PositiveIntegerField(default=0)),
                ('verified_users', models.PositiveIntegerField(default=0)),
                ('total_stories', models.PositiveIntegerField(default=0)),
                ('total_films', models.PositiveIntegerField(default=0)),
                ('total_content', models.PositiveIntegerField(default=0)),
                ('total_podcasts', models.PositiveIntegerField(default=0)),
                ('total_animations', models.PositiveIntegerField(default=0)),
                ('total_sneak_peeks', models.PositiveIntegerField(default=0)),
                ('total_live_videos', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_reading_time', models.PositiveIntegerField(default=0)),
                ('avg_session_duration', models.FloatField(default=0.0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('create_content', 'Create Content'), ('update_content', 'Update Content'), ('delete_content', 'Delete Content'), ('manage_user', 'Manage User'), ('delete_comment', 'Delete Comment'), ('feature_content', 'Feature Content'), ('ban_user', 'Ban User'), ('unban_user', 'Unban User'), ('make_admin', 'Make Admin'), ('remove_admin', 'Remove Admin'), ('bulk_action', 'Bulk Action')], max_length=50)),
                ('description', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_activities', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['admin', 'timestamp'], name='admin_dashb_admin_i_3f1909_idx'), models.Index(fields=['activity_type', 'timestamp'], name='admin_dashb_activit_44a9f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentModerationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('reason', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-submitted_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='admin_dashb_status_7426f0_idx'), models.Index(fields=['submitted_at'], name='admin_dashb_submitt_a3a095_idx')],
            },
        ),
    ]
